### ISSUE TITLE
Response content-type

### ISSUE THREAD

**Issue by oroger** [MiningPotatoes/PeriodicTable-API#1]
Hello, 

Thank you for sharing your project.
If I may I would suggest to add a response content type to match the actual content type.

At the moment the response are 

`Content-Type:text/html; charset=UTF-8`

It should be application/json as explained in [this post](http://stackoverflow.com/a/4064468/957103).

`header('Content-Type: application/json');`

**Comment by nickbclifford** [comment]
Thanks! Already on it.
